### ISSUE TITLE
ValueError: Sample larger than population or is negative

### ISSUE THREAD

**Issue by jieyang123** [cww97/visual-language-grasping#5]

**Comment by jieyang123** [comment]
config file:  utils/config.yaml
Creating data logging session: /home/lenovo/yangjie/RL/copys/visual-language-grasping/logs/2020-12-07.14:42:09TrainStage2
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    solver.main()
  File "main.py", line 20, in main
    self.stage_2_trainer.main()
  File "/home/lenovo/yangjie/RL/copys/visual-language-grasping/trainer/stage2trainer.py", line 179, in main
    self.training()
  File "/home/lenovo/yangjie/RL/copys/visual-language-grasping/trainer/stage2trainer.py", line 127, in training
    one_data = self._pack_one_data(k)
  File "/home/lenovo/yangjie/RL/copys/visual-language-grasping/trainer/stage2trainer.py", line 98, in _pack_one_data
    files = random.sample(files, k)
  File "/home/lenovo/.virtualenvs/py3/lib/python3.7/random.py", line 321, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

**Comment by jieyang123** [comment]
博主，您好，我跑代码的时候遇到了些问题，具体是下面这个问题，请问博主是我这边跑的命令不对，或者有解决的办法吗

**Comment by zhuhang0796** [comment]
我遇到了同样的问题，应该是缺少 ./logs/stage2data 下的something。
请问你现在解决了吗？
and 本项目的源码作者大佬可以帮助下吗？

**Comment by lk-greenbird** [comment]
请问你们解决这个问题了吗，是需要提前运行其他的命令吗

**Comment by zhangzhousuper** [comment]
一个简单的解决办法是下载之前commit的版本，具体是什么问题还没找出来
